# Redis Configuration — Demo BigData CH3
# ==========================================

# Network
port 6379
bind 0.0.0.0
protected-mode no

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Persistence — RDB Snapshot
save 900 1
save 300 10
save 60 10000

# Persistence — AOF
appendonly yes
appendfsync everysec

# Logging
loglevel notice
